/* Generated by scripts/prepare-media.mjs. Do not edit by hand. */

export const GENERATED_DOCUMENT_META: Record<string, { byteSize: number; digest: `0x${string}` }> = {
  "producer-001-declaration.pdf": {
    "byteSize": 2199,
    "digest": "0x5dff306da085b041b7d46120441109b3bbdcabbcbaeb1268632290168755d134"
  },
  "lot-001-record.pdf": {
    "byteSize": 2255,
    "digest": "0x560d75a6ecb796d9b9207a2efc27ebbdf9b7efbccef3997d8c54ef724054318d"
  },
  "lot-002-record.pdf": {
    "byteSize": 2237,
    "digest": "0x38eeb1cc16dedb05dc44c9e3daf1cb8a46f03c51430c36b5634b4b66d3df26b3"
  },
  "lot-003-record.pdf": {
    "byteSize": 2228,
    "digest": "0x6d0a2385fa18195c12afe063cc5eab05996a7f889d56ba700f27aaba8773a13c"
  },
  "lot-004-record.pdf": {
    "byteSize": 2226,
    "digest": "0xd7f4931aa008034b5b3146aaa2137591c52a5f593f1368c1ea0c8fa191cc0dcf"
  },
  "lot-005-record.pdf": {
    "byteSize": 2251,
    "digest": "0x2f3601218d46b61883546b2c8e57499cfe08033368c2d0bc8f28a07a6ecc8376"
  },
  "lot-006-record.pdf": {
    "byteSize": 2231,
    "digest": "0x532c4a39407f77a28cd86b44a48b011e12eb43643b391d4e94b0a46032639c7b"
  },
  "lot-001-review.pdf": {
    "byteSize": 2169,
    "digest": "0xc99bdeed0a0b5ea5e1036c4bcd3c9fa740eb549cbee6a6911f7253e3957ecfcf"
  },
  "lot-001-production.pdf": {
    "byteSize": 2001,
    "digest": "0xa66f5d9348591b62ef046b4c3b73919415dd83ffdfdc0a5e75d4e5afc4555add"
  },
  "lot-001-readiness.pdf": {
    "byteSize": 1996,
    "digest": "0x0cd16c0963aabbdb1b5452644429f0818cbae475ca7c2c9c0a26508b0ef2562f"
  },
  "redemption-001-shipment.pdf": {
    "byteSize": 1870,
    "digest": "0x07e3b58dc9066488073aa1731e2c4e5e628215c9b03670d6bb917b4c9327c6d8"
  }
};
