/**
 * English UI dictionary — the primary locale.
 *
 * Copy is taken verbatim from specifications/ui-mvp/05-content-and-demo-data.md
 * where that document specifies a string. Numbers, dates and identifiers are
 * always parameters, never baked into a phrase.
 */

export const en = {
  brand: {
    name: 'Palissage',
    tagline: 'Direct wine trade',
    skipToContent: 'Skip to content',
  },
  nav: {
    forWineries: 'For wineries',
    forBuyers: 'For buyers',
    howItWorks: 'How it works',
    pilot: 'Pilot',
    exploreDemo: 'Explore the demo',
    menu: 'Menu',
    closeMenu: 'Close menu',
    language: 'Language',
    overview: 'Overview',
    allocations: 'My allocations',
    secondary: 'Secondary market',
    deliveries: 'Deliveries',
    lots: 'Wine lots',
    finance: 'Payments & payouts',
    participants: 'Participants',
    verification: 'Lot reviews',
    redemptions: 'Redemptions',
    account: 'Account',
    exploreLots: 'Explore lots',
    workspace: 'Workspace',
  },
  role: {
    winery: 'Winery',
    buyer: 'Buyer',
    operations: 'Operations',
    visitor: 'Visitor',
  },
  mode: {
    demo: 'Demo · Sample data',
    testnet: 'Testnet · Test assets only',
    demoLong: 'Interactive demo · Fictional data · No real payments',
    testnetLong: 'Arbitrum Sepolia · Test assets only',
    mainnetDisabled: 'Mainnet is not enabled for this prototype',
    chooseEnvironment: 'Choose an environment',
    chooseEnvironmentBody: 'This workspace needs an explicit environment. The demo is self-contained; testnet uses a configured test network.',
    openDemo: 'Open interactive demo',
    openTestnet: 'Open testnet entry',
  },
  home: {
    eyebrow: 'DIRECT WINE TRADE',
    title: 'Good wine. A more direct route.',
    lead: 'Connect independent wineries with professional buyers. Reserve wine lots, follow their progress, and manage the journey from allocation to delivery.',
    primary: 'Explore the demo',
    secondary: 'Browse sample lots',
    demoNote: 'Interactive prototype. No wallet or real payment required.',
    imageCaption: 'From the vineyard to the buyer.',
    heroLotEyebrow: 'Les Terrasses · 2026',
    contextHeading: 'A closer relationship with every vintage.',
    contextBody: 'Wine trade depends on relationships, timing, and trust. Palissage brings offers, verification records, payments, and delivery steps into one shared workflow.',
    wineriesHeading: 'Bring your next vintage to new buyers.',
    wineriesBody: 'Offer current wine or open En Primeur reservations for a future release. Follow allocations, production milestones, and eligible payouts in one place.',
    wineriesPoints: [
      'Offer current and future lots',
      'Keep a clear record of each allocation',
      'Receive producer royalties on eligible secondary sales',
    ],
    wineriesCta: 'See the winery workflow',
    buyersHeading: 'Know the lot. Understand the terms.',
    buyersBody: 'Compare origins, quantities, release dates, and the evidence attached to each offer. Pay in full or use an available deposit option, then manage eligible resale and delivery from your workspace.',
    buyersCta: 'Explore the buyer workspace',
    stepsHeading: 'How it works',
    steps: [
      { title: 'Define the lot', body: 'A winery provides the wine, quantity, production stage, and supporting records.' },
      { title: 'Review the evidence', body: 'An authorised participant reviews the lot before it can be offered.' },
      { title: 'Reserve an allocation', body: 'An eligible buyer reviews the terms and pays in full or places a deposit.' },
      { title: 'Follow the progress', body: 'Production, balances, and eligible fund releases stay visible.' },
      { title: 'Receive the wine', body: 'Once the lot is ready, the holder requests delivery and confirms receipt.' },
    ],
    stepsBranch: 'Eligible resale',
    sampleHeading: 'A lot you can follow from start to finish.',
    sampleCta: 'View sample lot',
    recordHeading: 'The record behind the relationship.',
    recordBody: 'Digital records make allocations and their permitted transfers traceable. Contract rules coordinate payments and tokenised bottle balances. Physical verification and delivery still depend on the people and partners responsible for them.',
    recordPoints: ['Participant checks', 'Payment records', 'Delivery trail'],
    recordLink: 'Technical details',
    pilotHeading: 'From prototype to pilot.',
    pilotBody: 'Palissage is preparing the next stage with wineries, professional buyers, and ecosystem partners. Explore the planned milestones and the work required before real trading.',
    pilotCta: 'Read the pilot brief',
    faqHeading: 'Questions',
  },
  faq: {
    wallet: {
      q: 'Do I need a wallet to try it?',
      a: 'No. The guided demo uses sample data and simulated actions. The separate testnet experience requires a compatible wallet and test tokens.',
    },
    lot: {
      q: 'What does an allocation represent?',
      a: 'A reserved quantity belongs to an offer. In the protocol, tokenised bottle balances are created only after full payment. Physical delivery is a separate step.',
    },
    verify: {
      q: 'What does “verified” mean?',
      a: 'It identifies a completed review recorded for a participant or lot. Open the evidence panel to see the scope, reviewer, source, and date. A recorded hash alone does not prove the contents or physical condition of wine.',
    },
    deposit: {
      q: 'How does En Primeur work?',
      a: 'An offer can reserve a future release. Where a deposit is available, the remaining balance and payment deadline are shown before confirmation. Production dates are estimates unless the terms state otherwise.',
    },
    escrow: {
      q: 'Where does the payment go?',
      a: 'Primary-sale payments are held by the market contract. Winery withdrawals depend on authorised milestone confirmations and the contract’s accounting. Review the offer’s release rules before reserving.',
    },
    resale: {
      q: 'Can I resell my bottles?',
      a: 'Fully paid, available balances may be listed when the holder, lot, and market meet the transfer rules. A listing does not guarantee a buyer. The review shows the platform fee and producer royalty.',
    },
    delivery: {
      q: 'When can I request delivery?',
      a: 'When the lot is marked ready and your balance is eligible. Shipping, taxes, import conditions, and the delivery arrangement must be agreed separately. This demo does not ship wine.',
    },
    refund: {
      q: 'Can I cancel or get a refund?',
      a: 'Available actions depend on the allocation or delivery state and the contract rules. A refund request is not an automatic approval. Returning tokens from a delivery escrow is different from refunding a payment.',
    },
    real: {
      q: 'Are these real offers?',
      a: 'The public demo contains fictional producers, sample prices, and simulated transactions. Testnet records are labelled separately. Real trading is not enabled in this version.',
    },
  },
  marketplace: {
    title: 'Explore wine lots',
    lead: 'Compare sample offers from independent producers. Prices and availability in this catalogue are for demonstration.',
    tabs: { all: 'All lots', available: 'Available now', enPrimeur: 'En Primeur' },
    filters: {
      legend: 'Filters',
      producer: 'Producer',
      region: 'Region',
      vintage: 'Vintage',
      wineType: 'Wine type',
      price: 'Price per bottle',
      production: 'Production stage',
      verifiedOnly: 'Reviewed lots only',
      any: 'Any',
      min: 'Minimum',
      max: 'Maximum',
      open: 'Filters',
      apply: 'Show {count} lots',
      clear: 'Clear filters',
      remove: 'Remove filter {name}',
    },
    sort: {
      label: 'Sort',
      featured: 'Featured',
      priceAsc: 'Price: low to high',
      priceDesc: 'Price: high to low',
      readiness: 'Earliest readiness',
    },
    count: 'Showing {count} lots',
    searchPlaceholder: 'Search wine, producer, or region',
    searchLabel: 'Search lots',
    updating: 'Updating results…',
    pagination: 'Page {page} of {total}',
    previous: 'Previous page',
    next: 'Next page',
    sampleBadge: 'Sample lot',
  },
  lot: {
    breadcrumb: 'Explore lots',
    perBottle: 'Per bottle · 750 ml',
    availability: 'Available now',
    availableBottles: '{count} bottles available',
    soldOut: 'Fully allocated',
    offerType: 'Offer type',
    standard: 'Standard',
    enPrimeur: 'En Primeur',
    production: 'Production stage',
    expectedReadiness: 'Expected readiness',
    estimated: 'Estimated',
    reserve: 'Review purchase',
    quantity: 'Number of bottles',
    documents: 'Supporting documents',
    timeline: 'Production timeline',
    accounting: 'Lot accounting',
    totalCap: 'Total lot size',
    reservedNotMinted: 'Reserved, not yet issued',
    mintedOutstanding: 'Issued and held',
    escrowed: 'Held for delivery',
    redeemed: 'Delivered and retired',
    about: 'About this lot',
    producerSection: 'Producer',
    viewProducer: 'View producer',
    technical: 'Technical record',
    identifier: 'Identifier',
    contractStatus: 'Recorded lot status',
    evidenceAnchor: 'Evidence anchor',
    grapes: 'Grape varieties',
    bottleSize: 'Bottle size',
    alcohol: 'Alcohol by volume',
    volume: 'Volume',
    region: 'Region',
    vintage: 'Vintage',
    exportScope: 'Stated export scope',
    exportNote: 'A stated scope is not a completed import or export authorisation.',
    offerCloses: 'Reservations close',
    paymentDeadline: 'Balance payment deadline',
    offerUnavailable: 'This offer is not open for reservations.',
    closesIn: 'Closes {date}',
  },
  producer: {
    eyebrow: 'FICTIONAL PRODUCER · DEMONSTRATION',
    fictional: 'Fictional producer for the demo',
    location: 'Occitanie, France — sample location',
    offers: 'Available offers',
    records: 'Production and records',
    about: 'About this sample producer',
    noOffers: 'No open offers',
    tradeCta: 'Trade through Palissage',
  },
  demo: {
    title: 'Explore how a wine allocation moves from producer to delivery',
    snapshot: 'Data snapshot · {date} · Europe/Paris',
    start: 'Start the guided demo',
    resume: 'Resume demo',
    startOver: 'Start over',
    reset: 'Reset sample data',
    resetBody: 'This removes demo progress in this browser. Testnet transactions are unaffected.',
    resetConfirm: 'Reset sample data',
    role: 'View as {role}',
    chooseRole: 'Choose a role',
    exploreBuyer: 'Explore as buyer',
    exploreWinery: 'Explore as winery',
    exploreOperations: 'Explore operations',
    guidedTour: 'Guided tour',
    presets: 'Starting points',
    presetBuyerReady: 'Buyer ready',
    presetBuyerReadyBody: 'The main lot is reviewed and open, with 2,400 bottles available and no allocations yet.',
    presetProducerStart: 'Producer start',
    presetProducerStartBody: 'The main lot does not exist yet. Create it, submit it for review, and publish an offer.',
    presetDeliveryReady: 'Delivery ready',
    presetDeliveryReadyBody: '120 bottles are fully paid and the lot is ready, so delivery can be shown directly.',
    presetIssues: 'Exception branches',
    presetIssuesBody: 'A restricted lot, an expired qualification, a paused secondary market and a low balance.',
    presetActive: 'Current starting point',
    presetSwitch: 'Load this starting point',
    presetSwitchWarning: 'Loading a different starting point replaces the current sample progress.',
    advance: 'Advance simulated date',
    advanceBody: 'The simulated clock moves from {from} to {to}. Business records are not changed by this step.',
    stage: { balanceDue: '15 February 2027 — balance due', ready: '15 June 2027 — lot ready for delivery' },
    tourStep: 'Step {index} of {total}',
    tourNext: 'Next',
    tourPrevious: 'Previous',
    tourPause: 'Pause tour',
    tourResume: 'Resume tour',
    tourClose: 'Close tour',
    tourGo: 'Open this screen',
    tourFinished: 'Guided demo complete',
    tourFinishedBody: 'Every step in this scenario ran against the same sample ledger. Reset returns it to the starting point.',
    simulate: 'Simulate: {action}',
    simulationComplete: 'Simulation complete',
    localReference: 'Local demo reference',
    syntheticNotice: 'Fictional organisations, wines and prices. Nothing here places an order or moves real funds.',
    storedLocally: '{count} sample actions stored in this browser',
  },
  testnet: {
    title: 'Testnet entry',
    lead: 'This is a separate technical environment. It uses test assets on a configured test network and never touches real funds.',
    checks: 'Environment checks',
    checkChain: 'Network identifier',
    checkRpc: 'Network endpoint',
    checkAddresses: 'Contract addresses',
    checkBytecode: 'Deployed bytecode',
    checkToken: 'Payment token and decimals',
    checkAccount: 'Connected account',
    checkQualification: 'Participant qualification',
    observed: 'Observed',
    missing: 'Missing',
    failed: 'Failed',
    unavailable: 'Unavailable',
    connect: 'Connect wallet',
    enter: 'Enter workspace',
    blocked: 'Testnet setup is incomplete.',
    blockedBody: 'The deployment manifest for this build does not contain a validated testnet configuration, so no write action is offered here.',
    mainnet: 'Mainnet is not enabled for this prototype',
    noKeys: 'Never enter a seed phrase or private key. Palissage does not ask for them.',
    demoLink: 'Open interactive demo',
    supported: 'Supported actions',
    readOnly: 'Read-only in this build',
  },
  pilot: {
    title: 'Building the next route for wine trade.',
    sections: {
      who: 'Who the pilot serves',
      whoBody: 'Independent wineries with wine to place, and professional buyers who purchase repeatedly: wine shops, restaurants and importers. This is not a retail investment product.',
      what: 'What the prototype demonstrates',
      whatBody: 'Lot creation, review, reservation, balance payment, eligible resale and a delivery request. Simulated workflows and separately labelled testnet records.',
      stage: 'Current stage',
      stageBody: 'Prototype and testnet development. Mainnet trading is not enabled.',
      technology: 'Technology',
      technologyBody: 'Bottle balances, participant checks, controlled transfers, and payment records. The current repository targets an EVM test environment; deployment evidence is shown separately.',
      milestones: 'Next milestones',
      support: 'What support enables',
      supportBody: 'Engineering, UX validation, legal and operational preparation, an independent security review, and pilot onboarding.',
      enquiry: 'Prepare a pilot enquiry',
    },
    milestones: [
      'Complete the test workflow',
      'Validate with pilot participants',
      'Finalise operating and legal arrangements',
      'Independent security review',
      'Controlled live pilot',
    ],
    planned: 'Planned',
    form: {
      organisation: 'Organisation',
      contact: 'Contact name',
      email: 'Work email',
      role: 'Role',
      roleOptions: {
        winery: 'Winery',
        importer: 'Importer',
        shop: 'Wine shop',
        restaurant: 'Restaurant',
        other: 'Other professional',
      },
      country: 'Country',
      website: 'Website',
      message: 'Message',
      hint: 'Do not include payment details, identity documents, or commercially sensitive information.',
      submit: 'Download enquiry draft',
      success: 'Draft downloaded. Nothing has been sent.',
      privacy: 'Privacy',
    },
  },
  legal: {
    privacy: 'Privacy',
    prototype: 'Prototype notice',
    credits: 'Image credits',
    documentStatus: 'Draft · test environment',
    contents: 'On this page',
    prototypeBody: 'Palissage is a prototype for professional wine trade. Demo actions are simulated and do not place orders, transfer real funds, or arrange delivery. Testnet actions use test assets. Real commercial terms will be introduced before live trading.',
    privacyBody: 'The demo stores sample progress and your language choice in this browser. Resetting the demo removes its sample progress. Do not enter identity documents or sensitive personal information. The testnet experience may communicate your public wallet address and requests to configured network providers.',
    creditsBody: 'Illustrations in this prototype are generated for the demonstration and carry no third-party licence. Photographic material is only added through the asset manifest, with its source and licence recorded.',
    publisherPending: 'Publisher, legal entity and hosting details are added before any external publication. They are not invented here.',
  },
  footer: {
    purpose: 'A prototype for direct trade between independent wineries and professional buyers.',
    pilot: 'Pilot brief',
    testnet: 'Testnet',
    prototype: 'Prototype notice',
    privacy: 'Privacy',
    credits: 'Image credits',
    notice: 'Professional trade prototype · No real wine orders · 18+',
    health: '',
  },
  passport: {
    title: 'The story of this lot',
    sourceNote: 'Sample lot passport. Scanning this code does not verify a unique bottle or grant ownership.',
    demoLabel: 'Demonstration passport',
    wine: 'Wine',
    producer: 'Producer',
    timeline: 'Production timeline',
    records: 'Public records',
    copyLink: 'Copy link',
    explore: 'Explore Palissage',
    viewLot: 'View the public lot',
    notRecorded: 'Not recorded',
  },
  buyer: {
    overview: 'Overview',
    actionRequired: 'Action required',
    nothingDue: 'Nothing needs your attention right now.',
    remainderDue: 'Balance due',
    bottlesHeld: 'Bottles held',
    bottlesInEscrow: 'Bottles in delivery escrow',
    spendable: 'Sample balance',
    recentActivity: 'Recent activity',
    allocations: 'Allocations',
    tabs: { reservations: 'Reservations', balances: 'Bottle balances', history: 'History' },
    filters: { all: 'All', due: 'Payment due', paid: 'Fully paid', closed: 'Closed' },
    columns: {
      lot: 'Lot',
      producer: 'Producer',
      quantity: 'Original quantity',
      paid: 'Paid / total',
      due: 'Balance due',
      deadline: 'Deadline',
      state: 'State',
      action: 'Next action',
      walletQuantity: 'In wallet',
      frozen: 'Restricted',
      escrow: 'Delivery escrow',
      transferable: 'Available',
      reference: 'Reference',
      bottles: 'Bottles',
      winery: 'Winery',
      requested: 'Requested',
      price: 'Price / bottle',
      seller: 'Seller',
      available: 'Available',
      royalty: 'Producer royalty',
      remaining: 'Remaining',
      initial: 'Initial',
      date: 'Date',
      event: 'Event',
      source: 'Source',
    },
    payRemainder: 'Pay remaining balance',
    payRemainderDemo: 'Simulate balance payment',
    viewAllocation: 'View allocation',
    viewPosition: 'View bottle position',
    allocationDetail: 'Allocation detail',
    paymentSchedule: 'Payment schedule',
    bottleAccounting: 'Bottle accounting',
    ownershipNote: 'Tokens are created after full payment.',
    position: 'Bottle position',
    acquisitions: 'Acquisitions and transfers',
    listForResale: 'Create resale offer',
    requestDelivery: 'Request delivery',
    secondary: 'Secondary market',
    secondaryTabs: { browse: 'Browse listings', mine: 'My listings' },
    secondaryContext: 'Resale moves existing bottle rights between eligible buyers. Each sale pays a producer royalty.',
    createListing: 'Create resale offer',
    cancelListing: 'Cancel listing',
    viewListing: 'View listing',
    buyListing: 'Review purchase',
    deliveries: 'Deliveries',
    deliveryDetail: 'Delivery detail',
    confirmReceipt: 'Confirm receipt',
    reportProblem: 'Report a delivery problem',
    cancelRequest: 'Cancel request',
    destination: 'Delivery destination',
    shipmentDocuments: 'Shipment documents',
    supportCases: 'Support cases',
    reserveTitle: 'Reserve an allocation',
    steps: { terms: 'Terms', review: 'Review', result: 'Result' },
    paymentChoice: 'Payment',
    payFull: 'Pay in full',
    payDeposit: 'Pay minimum deposit',
    acknowledge: 'I understand this is a test environment and no real wine is ordered.',
    account: 'Account and eligibility',
  },
  winery: {
    overview: 'Overview',
    lots: 'Wine lots',
    createLot: 'Create lot draft',
    lotDetail: 'Manage lot',
    finance: 'Payments & payouts',
    deliveries: 'Deliveries',
    fundsReceived: 'Received gross',
    feesDeducted: 'Protocol fees deducted',
    netCredited: 'Net credited',
    lockedEscrow: 'Held under release rules',
    withdrawable: 'Available to withdraw',
    withdrawn: 'Already withdrawn',
    royaltiesEarned: 'Producer royalties',
    tabs: {
      overview: 'Overview',
      documents: 'Documents',
      offers: 'Offers',
      production: 'Production',
      history: 'History',
      escrow: 'Primary escrow',
      royalties: 'Royalties',
      withdrawals: 'Withdrawals',
    },
    wizard: {
      identity: 'Wine identity',
      quantity: 'Quantity and production',
      evidence: 'Evidence',
      review: 'Review',
      next: 'Continue',
      back: 'Back',
      createDraft: 'Create lot draft',
      submit: 'Submit for review',
      draftNote: 'A saved draft stays in this browser until the lot is created.',
    },
    createOffer: 'Create offer',
    publishOffer: 'Publish offer',
    cancelOffer: 'Cancel offer',
    advanceProduction: 'Update production stage',
    submitEvidence: 'Submit milestone evidence',
    withdraw: 'Withdraw available funds',
    recordShipment: 'Record shipment',
    exportCsv: 'Download displayed rows (CSV)',
    milestones: 'Release milestones',
    milestoneReleased: 'Released',
    milestonePending: 'Awaiting confirmation',
    remaining: 'Still offerable',
    noOffers: 'No offers published for this lot yet.',
    offerable: '{count} bottles can still be offered',
    account: 'Account and eligibility',
  },
  operations: {
    overview: 'Operational queues',
    banner: 'Demo operations workspace',
    participants: 'Participants',
    participantDetail: 'Participant review',
    verification: 'Lot reviews',
    verificationDetail: 'Lot evidence and decisions',
    redemptions: 'Redemptions',
    redemptionDetail: 'Redemption case',
    queues: {
      participants: 'Participants awaiting review',
      lots: 'Lots awaiting review',
      milestones: 'Milestones awaiting confirmation',
      cases: 'Open delivery cases',
    },
    tabs: { lots: 'Lots', milestones: 'Milestones' },
    decision: 'Decision',
    approve: 'Approve',
    requestChanges: 'Request changes',
    reject: 'Reject submission',
    recordReview: 'Record lot review',
    confirmMilestone: 'Confirm milestone',
    checklist: 'Review checklist',
    checklistItems: [
      'Organisation evidence has been opened',
      'Participant role matches the declared activity',
      'Applicable claim topics are present',
      'Scope and country declaration reviewed',
    ],
    lotChecklist: [
      'Declared producer matches the lot owner',
      'Quantity and bottle size are consistent with the record',
      'Provenance evidence has been opened',
      'Production stage matches the submitted documents',
    ],
    grants: 'Contract permissions',
    grantsNote: 'Each permission is read from the contract that holds it. A business role never widens it.',
    refreshGrants: 'Refresh permissions',
    resolveCase: 'Resolve case',
    outcomeDelivery: 'Confirm delivery',
    outcomeReturn: 'Return tokenised bottles',
    outcomeReturnNote: 'Return the escrowed bottle tokens. No money refund is made by this action.',
    enforcement: 'Enforcement and recovery',
    enforcementBody: 'Freeze, forced transfer and escrow recovery need a separate specialist workflow with its own authorisation. They are shown here read-only and are not part of the ordinary review path.',
    account: 'Account and capabilities',
  },
  price: {
    unit: 'Per bottle · 750 ml',
    exclusions: 'Wine allocation price. Shipping, taxes, duties, and network fees are not included in this example.',
    settlementNote: 'Shipping and applicable taxes require a separate quote.',
    precision: 'Token settlement precision',
    exactAmount: 'Exact amount',
  },
  order: {
    total: 'Allocation total',
    deposit: 'Deposit due now',
    balance: 'Remaining balance',
    payNow: 'Payment now',
    deadline: 'Balance due by {date}',
    reserveDemo: 'Simulate reservation',
    reserveTest: 'Reserve {quantity} bottles',
    payDemo: 'Simulate balance payment',
    payTest: 'Pay remaining balance',
    feeIncluded: '{rate} platform fee is included in the gross amount and deducted from the winery payout.',
    quantityUnit: 'bottles',
  },
  approval: {
    title: 'Allow the payment',
    body: 'This permission allows the market contract to spend the displayed amount. It does not reserve bottles.',
    done: 'Permission confirmed. Continue to reserve.',
  },
  tx: {
    wallet: 'Confirm in your wallet',
    pending: 'Transaction submitted. Waiting for confirmation.',
    checking: 'Checking the updated record…',
    rejected: 'Request declined. No new transaction was submitted.',
    unknown: 'Confirmation is taking longer. Check the transaction before trying again.',
    reverted: 'The transaction failed. Your allocation has not changed. Network fees may still apply.',
    confirm: 'Confirm',
    review: 'Review',
    consequences: 'What happens next',
    working: 'Working…',
  },
  reserve: {
    done: '{quantity} bottles reserved. Deposit recorded.',
    depositNote: 'Tokens are created after full payment.',
  },
  paid: { done: 'Fully paid · {quantity} bottles' },
  secondary: {
    list: 'Create resale offer',
    royalty: 'Producer royalty',
    proceeds: 'Seller receives',
    fee: 'Platform fee',
    gross: 'Buyer pays',
    unitPrice: 'Price per bottle',
    listingRemaining: '{remaining} of {initial} bottles remaining',
    noExpiry: 'A listing has no expiry of its own. The quote you confirm at purchase has a short deadline.',
    unavailable: 'Unavailable',
    unavailableBody: 'The seller balance moved after this listing was created, so it cannot be filled right now.',
  },
  delivery: {
    request: 'Request delivery',
    escrow: 'Requested bottles are held while delivery is open.',
    confirm: 'Confirm receipt',
    confirmBody: 'Confirm only after receiving the wine. Completing this step closes the request and retires its tokenised bottle balance.',
    confirmCheckbox: 'I confirm receipt of the wine described above',
    problem: 'Report a delivery problem',
    tokenReturn: 'Tokenised bottle balance restored',
    logisticsNote: 'Logistics, shipping cost, taxes and duties are agreed separately. This request does not book a carrier.',
    recorded: 'Shipment recorded',
    noTracking: 'No carrier tracking is connected in this build.',
    useFictional: 'Use fictional details',
    categories: {
      missing: 'Missing shipment',
      damaged: 'Damaged or incomplete',
      documentation: 'Documentation',
      other: 'Other',
    },
    description: 'Description',
    prepareRequest: 'Prepare support request',
  },
  common: {
    evidence: 'View evidence',
    technical: 'Technical record',
    retry: 'Try again',
    back: 'Back',
    cancel: 'Cancel',
    close: 'Close',
    saveDraft: 'Save draft',
    saved: 'Draft saved in this browser',
    notProvided: 'Not provided',
    notProvidedSample: 'Not provided in this sample',
    copy: 'Copy',
    copyDone: 'Copied',
    download: 'Download record',
    loading: 'Loading',
    updating: 'Updating',
    lastUpdated: 'Last updated {time}',
    source: 'Source',
    showMore: 'Show more',
    showLess: 'Show less',
    required: 'Required',
    optional: 'Optional',
    continue: 'Continue',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    all: 'All',
    none: 'None',
    search: 'Search',
    of: 'of',
    unknown: 'Unknown',
    viewAll: 'View all',
    openDocument: 'Open document',
    documentMeta: '{type} · {size}',
    sampleDocument: 'Sample document',
    demoVerification: 'Demo verification',
    illustrative: 'Illustrative photography',
    illustrativeImage: 'Illustration generated for this demonstration',
    errorSummary: 'Check the following',
    unsavedChanges: 'Unsaved changes',
    keepEditing: 'Keep editing',
    discard: 'Discard changes',
    remove: 'Remove',
    add: 'Add',
    step: 'Step',
    quantityAvailable: '{count} available',
  },
  status: {
    lot: {
      Draft: 'Draft',
      Verified: 'Lot review recorded',
      Suspended: 'Lot restricted',
      Closed: 'Lot closed',
    },
    production: {
      Announced: 'Announced',
      Growing: 'Growing',
      Harvested: 'Harvested',
      Vinification: 'Vinification',
      Aging: 'Ageing',
      Bottled: 'Bottled',
      ReadyForDelivery: 'Ready for delivery',
    },
    allocation: {
      Reserved: 'Reserved · Payment due',
      Paid: 'Fully paid',
      Cancelled: 'Reservation cancelled',
      Defaulted: 'Payment default recorded',
    },
    redemption: {
      Requested: 'Delivery requested',
      Shipped: 'Shipment recorded',
      Completed: 'Receipt confirmed',
      Cancelled: 'Delivery request cancelled',
    },
    review: {
      draft: 'Draft',
      submitted: 'Awaiting review',
      needs_changes: 'Changes requested',
      accepted: 'Review accepted',
      rejected: 'Review rejected',
    },
    case: {
      open: 'Delivery problem reported',
      under_review: 'Case under review',
      resolved_delivery: 'Case resolved · delivery confirmed',
      resolved_return: 'Case resolved · bottles returned',
    },
    offer: {
      open: 'Open for reservations',
      scheduled: 'Opens {date}',
      ended: 'Reservations closed',
      sold_out: 'Fully allocated',
      cancelled: 'Offer withdrawn',
    },
    listing: { active: 'Active', sold: 'Filled', cancelled: 'Cancelled', unavailable: 'Unavailable' },
    overdue: 'Payment overdue',
  },
  field: {
    wineName: 'Wine name',
    vintage: 'Vintage',
    region: 'Region',
    country: 'Country',
    grapes: 'Grape varieties',
    bottleSize: 'Bottle size',
    alcohol: 'Alcohol by volume',
    quantity: 'Number of bottles',
    price: 'Price per bottle',
    deposit: 'Deposit percentage',
    saleStart: 'Reservations open',
    saleEnd: 'Reservations close',
    paymentDeadline: 'Balance payment deadline',
    expectedReady: 'Expected readiness date',
    documents: 'Supporting documents',
    organisation: 'Organisation',
    contact: 'Contact name',
    email: 'Work email',
    phone: 'Phone number',
    address: 'Delivery address',
    addressLine2: 'Address line 2',
    city: 'City',
    postcode: 'Postal code',
    notes: 'Notes',
    reason: 'Reason for this decision',
    royalty: 'Producer royalty',
    offerType: 'Offer type',
    carrier: 'Carrier',
    trackingReference: 'Shipment reference',
    shippedDate: 'Shipment date',
    trackingUrl: 'Tracking link',
    percentage: 'Percentage',
    grapeName: 'Variety',
  },
  action: {
    createLot: 'Create lot draft',
    submitReview: 'Submit for review',
    requestChanges: 'Request changes',
    recordReview: 'Record lot review',
    publishOffer: 'Publish offer',
    updateProduction: 'Update production stage',
    confirmMilestone: 'Confirm milestone',
    withdraw: 'Withdraw available funds',
    markShipped: 'Record shipment',
    returnTokens: 'Return tokenised bottles',
  },
  activity: {
    'allocation.reserved': '{actor} reserved {quantity} bottles',
    'allocation.paid': '{actor} paid the balance',
    'listing.created': '{actor} listed {quantity} bottles',
    'listing.cancelled': '{actor} cancelled a listing',
    'listing.filled': '{actor} bought {quantity} bottles on the secondary market',
    'redemption.requested': '{actor} requested delivery',
    'redemption.shipped': '{actor} marked the shipment',
    'redemption.completed': '{actor} confirmed receipt',
    'redemption.cancelled': '{actor} cancelled the delivery request',
    'redemption.refunded': '{actor} returned the escrowed bottles',
    'lot.created': '{actor} created a lot draft',
    'lot.submitted': '{actor} submitted the lot for review',
    'lot.changes_requested': '{actor} requested changes to the lot',
    'lot.verified': '{actor} recorded the lot review',
    'lot.production': '{actor} updated the production stage',
    'offer.published': '{actor} published an offer',
    'offer.cancelled': '{actor} withdrew an offer',
    'milestone.evidence': '{actor} submitted milestone evidence',
    'milestone.confirmed': '{actor} confirmed a release milestone',
    'funds.withdrawn': '{actor} withdrew available funds',
    'case.opened': '{actor} reported a delivery problem',
    'case.resolved': '{actor} resolved the delivery case',
    'participant.reviewed': '{actor} recorded a participant review',
    'clock.advanced': 'Simulated date advanced',
  },
  empty: {
    noResults: { title: 'No matching lots', body: 'Try another producer, vintage, or price range.', action: 'Clear filters' },
    noAllocations: {
      title: 'Your next allocation starts here',
      body: 'Explore sample offers and review their terms.',
      action: 'Browse lots',
    },
    noDeliveries: {
      title: 'No delivery requests yet',
      body: 'Ready and fully paid bottles can be requested from your allocations.',
      action: 'View allocations',
    },
    noListings: {
      title: 'No listings yet',
      body: 'Eligible holdings can be offered for resale from a bottle position.',
      action: 'View bottle balances',
    },
    noQueue: { title: 'No items awaiting review', body: 'New submissions appear here as participants send them.', action: '' },
    noLots: { title: 'No lots yet', body: 'Create a lot draft with its quantity, production stage and records.', action: 'Create lot draft' },
    noActivity: { title: 'No activity yet', body: 'Actions taken in this scenario are listed here.', action: '' },
  },
  errors: {
    wrongNetwork: { title: 'Switch to {network}', body: 'This testnet action is unavailable on the current network.', action: 'Switch network' },
    unverifiedBuyer: {
      title: 'Participant review required',
      body: 'Your account needs the required buyer checks before reserving.',
      action: 'View account',
    },
    rpcUnavailable: {
      title: 'Network records are unavailable',
      body: 'Your existing data has not been replaced. Reconnect to refresh it.',
      action: 'Try again',
    },
    lotUnavailable: {
      title: 'This lot is unavailable',
      body: 'The lot could not be found in the selected environment.',
      action: 'Back to catalogue',
    },
    readOnly: {
      title: 'Action unavailable in this environment',
      body: 'The required integration or permission is not available.',
      action: 'View details',
    },
    frozen: {
      title: 'This balance cannot be used right now',
      body: 'Review the restriction and the available support path.',
      action: 'View restriction',
    },
    soldOut: {
      title: 'Fully allocated',
      body: 'This primary offer has no available quantity.',
      action: 'Explore secondary offers',
    },
    notFound: { title: 'Not found', body: 'This {entity} does not exist in the selected environment.', action: 'Back' },
    generic: 'We couldn’t complete this action. Your last confirmed record is shown.',
    persistedVersion: {
      title: 'Sample progress could not be restored',
      body: 'The stored demo session does not match this version. Resetting it starts a clean scenario.',
      action: 'Reset sample data',
    },
  },
  reason: {
    UNKNOWN: 'This check could not be completed, so the action stays unavailable.',
    NOT_CONNECTED: 'Choose a role in the demo, or connect an account in testnet.',
    WRONG_ROLE: 'This account holds a different role in the workflow.',
    NOT_OWNER: 'This record belongs to another organisation.',
    NOT_ELIGIBLE: 'Your account needs the required buyer checks before reserving.',
    ELIGIBILITY_EXPIRED: 'A required qualification has expired and needs a new review.',
    LOT_NOT_VERIFIED: 'This lot has not completed its review.',
    LOT_SUSPENDED: 'This lot is temporarily restricted.',
    LOT_CLOSED: 'This lot is closed.',
    MARKET_PAUSED: 'This market is paused, so the action is temporarily restricted.',
    OFFER_NOT_OPEN: 'This offer is not open for reservations.',
    OFFER_SOLD_OUT: 'This primary offer has no available quantity.',
    DEADLINE_PASSED: 'The payment deadline has passed.',
    NOT_READY_FOR_DELIVERY: 'Delivery opens once the lot is marked ready.',
    NO_TRANSFERABLE_BALANCE: 'There are no available bottles in this position.',
    BALANCE_FROZEN: 'This balance is restricted and cannot be used right now.',
    NOTHING_WITHDRAWABLE: 'No confirmed release is available to withdraw.',
    ALREADY_SETTLED: 'This step is already complete.',
    WRONG_STATE: 'The record is not in a state that allows this action.',
    MISSING_EVIDENCE: 'The required evidence has not been provided.',
    MISSING_CONTRACT_ROLE: 'Your account does not hold the permission this contract requires.',
    INTEGRATION_UNAVAILABLE: 'The required integration is not available in this build.',
    SELF_TRADE: 'A seller cannot buy their own listing.',
    INSUFFICIENT_FUNDS: 'Insufficient test token balance.',
    QUOTE_CHANGED: 'The quote changed or expired.',
    STALE_SNAPSHOT: 'The records changed while this review was open. Review the updated figures.',
    DUPLICATE_REQUEST: 'This action was already submitted.',
  },
  validation: {
    required: 'This field is required.',
    tooShort: 'Use at least {min} characters.',
    tooLong: 'Use at most {max} characters.',
    email: 'Enter a valid email address.',
    url: 'Enter a valid address.',
    https: 'Use an https:// address.',
    wholeNumber: 'Enter a whole number.',
    quantityRange: 'Enter a whole number of bottles, from {min} to {max}.',
    quantityStep: 'Use a multiple of {step} bottles.',
    noneAvailable: 'No bottles are available for this action.',
    priceFormat: 'Enter an amount such as {example}.',
    pricePrecision: 'Use at most {decimals} decimal places.',
    pricePositive: 'Enter an amount greater than zero.',
    vintageRange: 'Enter a year between {min} and {max}.',
    abvFormat: 'Enter a value such as {example}.',
    abvRange: 'Enter a value between {min} and {max}.',
    percentageRange: 'Enter a percentage between 0 and 100.',
    percentageSum: 'The percentages add up to {sum}. They must total 100 when every variety has one.',
    tooManyRows: 'Add at most {max} varieties.',
    endAfterStart: 'The closing date must be after the opening date.',
    deadlineAfterEnd: 'The payment deadline cannot be before reservations close.',
    depositRange: 'Enter a deposit between 1% and 99%.',
    depositBelowPrecision: 'Deposit amount is below supported precision.',
    enPrimeurProduction: 'En Primeur applies before bottling.',
    postalCodeFr: 'A French postal code has five digits.',
    summary: 'Check {count} fields before continuing.',
  },
  a11y: {
    mainNavigation: 'Main navigation',
    workspaceNavigation: 'Workspace navigation',
    breadcrumb: 'Breadcrumb',
    sortBy: 'Sort results by',
    increase: 'Increase quantity',
    decrease: 'Decrease quantity',
    openMenu: 'Open menu',
    resultsUpdated: '{count} lots found',
    dialog: 'Review dialog',
    progress: 'Progress',
    lotImage: 'Illustration of the {name} sample bottle',
    heroImage: 'Vineyard rows illustration generated for this demonstration',
    estateImage: 'Wine cellar illustration generated for this demonstration',
  },
};

export type Dictionary = typeof en;
