/**
 * French UI dictionary.
 *
 * Typed as `Dictionary`, so a missing or misspelled key fails the build rather
 * than silently falling back to an English string. Copy specified in
 * 05-content-and-demo-data.md is used verbatim.
 */

import type { Dictionary } from './en';

export const fr: Dictionary = {
  brand: {
    name: 'Palissage',
    tagline: 'Commerce direct du vin',
    skipToContent: 'Aller au contenu',
  },
  nav: {
    forWineries: 'Pour les domaines',
    forBuyers: 'Pour les acheteurs',
    howItWorks: 'Comment ça marche',
    pilot: 'Projet pilote',
    exploreDemo: 'Explorer la démo',
    menu: 'Menu',
    closeMenu: 'Fermer le menu',
    language: 'Langue',
    overview: 'Vue d’ensemble',
    allocations: 'Mes réservations et bouteilles',
    secondary: 'Marché secondaire',
    deliveries: 'Livraisons',
    lots: 'Lots de vin',
    finance: 'Paiements et versements',
    participants: 'Participants',
    verification: 'Examen des lots',
    redemptions: 'Livraisons à examiner',
    account: 'Compte',
    exploreLots: 'Explorer les lots',
    workspace: 'Espace de travail',
  },
  role: {
    winery: 'Domaine',
    buyer: 'Acheteur',
    operations: 'Opérations',
    visitor: 'Visiteur',
  },
  mode: {
    demo: 'Démo · Données fictives',
    testnet: 'Testnet · Actifs de test uniquement',
    demoLong: 'Démo interactive · Données fictives · Aucun paiement réel',
    testnetLong: 'Arbitrum Sepolia · Actifs de test uniquement',
    mainnetDisabled: 'Le réseau principal n’est pas activé pour ce prototype',
    chooseEnvironment: 'Choisir un environnement',
    chooseEnvironmentBody:
      'Cet espace nécessite un environnement explicite. La démo fonctionne seule ; le testnet utilise un réseau de test configuré.',
    openDemo: 'Ouvrir la démo interactive',
    openTestnet: 'Ouvrir l’accès testnet',
  },
  home: {
    eyebrow: 'COMMERCE DIRECT DU VIN',
    title: 'Le bon vin. Un lien plus direct.',
    lead: 'Relier les domaines indépendants aux acheteurs professionnels. Réservez des lots de vin, suivez leur évolution et gérez chaque étape, de la réservation à la livraison.',
    primary: 'Explorer la démo',
    secondary: 'Voir les lots de démonstration',
    demoNote: 'Prototype interactif. Aucun portefeuille ni paiement réel requis.',
    imageCaption: 'Du vignoble à l’acheteur.',
    heroLotEyebrow: 'Les Terrasses · 2026',
    contextHeading: 'Un lien plus étroit, à chaque millésime.',
    contextBody:
      'Le commerce du vin repose sur les relations, les délais et la confiance. Palissage réunit les offres, les justificatifs, les paiements et les étapes de livraison dans un parcours commun.',
    wineriesHeading: 'Présentez votre prochain millésime à de nouveaux acheteurs.',
    wineriesBody:
      'Proposez vos vins disponibles ou ouvrez les réservations en primeur de votre future production. Suivez les réservations, les étapes de production et les versements disponibles au même endroit.',
    wineriesPoints: [
      'Proposer des lots disponibles et futurs',
      'Suivre clairement chaque réservation',
      'Recevoir une redevance sur les reventes éligibles',
    ],
    wineriesCta: 'Découvrir le parcours domaine',
    buyersHeading: 'Connaître le lot. Comprendre les conditions.',
    buyersBody:
      'Comparez les origines, les quantités, les dates de disponibilité et les justificatifs de chaque offre. Réglez la totalité ou utilisez l’acompte proposé, puis gérez la revente éligible et la livraison depuis votre espace.',
    buyersCta: 'Découvrir l’espace acheteur',
    stepsHeading: 'Comment ça marche',
    steps: [
      { title: 'Définir le lot', body: 'Le domaine renseigne le vin, la quantité, l’étape de production et les justificatifs.' },
      { title: 'Examiner les justificatifs', body: 'Un intervenant habilité examine le lot avant sa mise en vente.' },
      { title: 'Réserver une quantité', body: 'L’acheteur éligible consulte les conditions et règle le prix ou un acompte.' },
      { title: 'Suivre l’avancement', body: 'La production, les soldes et les versements éligibles restent visibles.' },
      { title: 'Recevoir le vin', body: 'Lorsque le lot est prêt, le détenteur demande la livraison et confirme la réception.' },
    ],
    stepsBranch: 'Revente éligible',
    sampleHeading: 'Un lot à suivre du début à la fin.',
    sampleCta: 'Voir le lot de démonstration',
    recordHeading: 'Une trace au service de la relation.',
    recordBody:
      'Les enregistrements numériques rendent les réservations et leurs transferts autorisés traçables. Les règles des contrats coordonnent les paiements et les soldes de bouteilles tokenisées. La vérification physique et la livraison restent assurées par les personnes et partenaires responsables.',
    recordPoints: ['Vérification des participants', 'Historique des paiements', 'Suivi de livraison'],
    recordLink: 'Détails techniques',
    pilotHeading: 'Du prototype au projet pilote.',
    pilotBody:
      'Palissage prépare la prochaine étape avec les domaines, les acheteurs professionnels et les partenaires de l’écosystème. Découvrez les jalons prévus et le travail nécessaire avant les échanges réels.',
    pilotCta: 'Consulter le projet pilote',
    faqHeading: 'Questions',
  },
  faq: {
    wallet: {
      q: 'Faut-il un portefeuille pour essayer ?',
      a: 'Non. La visite guidée utilise des données fictives et des actions simulées. L’expérience testnet séparée nécessite un portefeuille compatible et des jetons de test.',
    },
    lot: {
      q: 'Que représente une réservation ?',
      a: 'Une quantité réservée est liée à une offre. Dans le protocole, les soldes de bouteilles tokenisées ne sont créés qu’après paiement intégral. La livraison physique constitue une étape distincte.',
    },
    verify: {
      q: 'Que signifie « vérifié » ?',
      a: 'Il s’agit d’un examen enregistré pour un participant ou un lot. Consultez les justificatifs pour connaître son périmètre, son auteur, sa source et sa date. Une empreinte numérique seule ne prouve ni le contenu ni l’état physique du vin.',
    },
    deposit: {
      q: 'Comment fonctionne l’achat en primeur ?',
      a: 'Une offre peut porter sur une production future. Si un acompte est proposé, le solde et l’échéance sont affichés avant confirmation. Les dates de production sont prévisionnelles, sauf indication contraire dans les conditions.',
    },
    escrow: {
      q: 'Où va le paiement ?',
      a: 'Les paiements du marché primaire sont conservés par le contrat de marché. Les retraits du domaine dépendent des jalons confirmés par les personnes habilitées et de la comptabilité du contrat. Consultez les règles de versement avant de réserver.',
    },
    resale: {
      q: 'Puis-je revendre mes bouteilles ?',
      a: 'Les soldes disponibles et intégralement payés peuvent être proposés lorsque le détenteur, le lot et le marché respectent les règles de transfert. Une annonce ne garantit pas un acheteur. Le récapitulatif indique les frais de plateforme et la redevance du domaine.',
    },
    delivery: {
      q: 'Quand demander la livraison ?',
      a: 'Lorsque le lot est indiqué comme prêt et que votre solde est éligible. Le transport, les taxes, les conditions d’importation et les modalités de livraison doivent être convenus séparément. Cette démo n’expédie pas de vin.',
    },
    refund: {
      q: 'Puis-je annuler ou être remboursé ?',
      a: 'Les actions disponibles dépendent de l’état de la réservation ou de la livraison et des règles du contrat. Une demande de remboursement n’est pas une acceptation automatique. Le retour des jetons d’un séquestre de livraison est distinct du remboursement d’un paiement.',
    },
    real: {
      q: 'S’agit-il d’offres réelles ?',
      a: 'La démo publique contient des producteurs fictifs, des prix d’exemple et des transactions simulées. Les enregistrements testnet sont indiqués séparément. Les échanges réels ne sont pas activés dans cette version.',
    },
  },
  marketplace: {
    title: 'Explorer les lots de vin',
    lead: 'Comparez des offres de démonstration de producteurs indépendants. Les prix et disponibilités de ce catalogue sont fictifs.',
    tabs: { all: 'Tous les lots', available: 'Disponibles', enPrimeur: 'En primeur' },
    filters: {
      legend: 'Filtres',
      producer: 'Producteur',
      region: 'Région',
      vintage: 'Millésime',
      wineType: 'Type de vin',
      price: 'Prix par bouteille',
      production: 'Étape de production',
      verifiedOnly: 'Lots examinés uniquement',
      any: 'Tous',
      min: 'Minimum',
      max: 'Maximum',
      open: 'Filtres',
      apply: 'Afficher {count} lots',
      clear: 'Effacer les filtres',
      remove: 'Retirer le filtre {name}',
    },
    sort: {
      label: 'Trier',
      featured: 'Sélection',
      priceAsc: 'Prix croissant',
      priceDesc: 'Prix décroissant',
      readiness: 'Disponibilité la plus proche',
    },
    count: '{count} lots affichés',
    searchPlaceholder: 'Rechercher un vin, un producteur ou une région',
    searchLabel: 'Rechercher des lots',
    updating: 'Actualisation des résultats…',
    pagination: 'Page {page} sur {total}',
    previous: 'Page précédente',
    next: 'Page suivante',
    sampleBadge: 'Lot de démonstration',
  },
  lot: {
    breadcrumb: 'Explorer les lots',
    perBottle: 'Par bouteille · 750 ml',
    availability: 'Disponible',
    availableBottles: '{count} bouteilles disponibles',
    soldOut: 'Entièrement attribué',
    offerType: 'Type d’offre',
    standard: 'Standard',
    enPrimeur: 'En primeur',
    production: 'Étape de production',
    expectedReadiness: 'Disponibilité prévue',
    estimated: 'Prévisionnel',
    reserve: 'Examiner l’achat',
    quantity: 'Nombre de bouteilles',
    documents: 'Justificatifs',
    timeline: 'Étapes de production',
    accounting: 'Comptabilité du lot',
    totalCap: 'Taille totale du lot',
    reservedNotMinted: 'Réservé, pas encore émis',
    mintedOutstanding: 'Émis et détenu',
    escrowed: 'Bloqué pour livraison',
    redeemed: 'Livré et retiré',
    about: 'À propos de ce lot',
    producerSection: 'Producteur',
    viewProducer: 'Voir le producteur',
    technical: 'Enregistrement technique',
    identifier: 'Identifiant',
    contractStatus: 'Statut du lot enregistré',
    evidenceAnchor: 'Empreinte des justificatifs',
    grapes: 'Cépages',
    bottleSize: 'Contenance',
    alcohol: 'Titre alcoométrique',
    volume: 'Volume',
    region: 'Région',
    vintage: 'Millésime',
    exportScope: 'Périmètre d’export déclaré',
    exportNote: 'Un périmètre déclaré ne constitue pas une autorisation d’import ou d’export.',
    offerCloses: 'Clôture des réservations',
    paymentDeadline: 'Échéance du solde',
    offerUnavailable: 'Cette offre n’est pas ouverte aux réservations.',
    closesIn: 'Clôture le {date}',
  },
  producer: {
    eyebrow: 'PRODUCTEUR FICTIF · DÉMONSTRATION',
    fictional: 'Producteur fictif pour la démonstration',
    location: 'Occitanie, France — lieu fictif',
    offers: 'Offres disponibles',
    records: 'Production et justificatifs',
    about: 'À propos de ce producteur fictif',
    noOffers: 'Aucune offre ouverte',
    tradeCta: 'Commercer via Palissage',
  },
  demo: {
    title: 'Découvrez le parcours d’une réservation, du producteur à la livraison',
    snapshot: 'Données au {date} · Europe/Paris',
    start: 'Lancer la visite guidée',
    resume: 'Reprendre la démo',
    startOver: 'Recommencer',
    reset: 'Réinitialiser les données fictives',
    resetBody:
      'Cette action efface la progression de démonstration dans ce navigateur. Les transactions testnet restent inchangées.',
    resetConfirm: 'Réinitialiser les données fictives',
    role: 'Voir en tant que {role}',
    chooseRole: 'Choisir un rôle',
    exploreBuyer: 'Explorer en tant qu’acheteur',
    exploreWinery: 'Explorer en tant que domaine',
    exploreOperations: 'Explorer les opérations',
    guidedTour: 'Visite guidée',
    presets: 'Points de départ',
    presetBuyerReady: 'Acheteur prêt',
    presetBuyerReadyBody:
      'Le lot principal est examiné et ouvert, avec 2 400 bouteilles disponibles et aucune réservation.',
    presetProducerStart: 'Départ producteur',
    presetProducerStartBody:
      'Le lot principal n’existe pas encore. Créez-le, soumettez-le à l’examen et publiez une offre.',
    presetDeliveryReady: 'Livraison prête',
    presetDeliveryReadyBody:
      '120 bouteilles sont intégralement payées et le lot est prêt : la livraison peut être montrée directement.',
    presetIssues: 'Branches d’exception',
    presetIssuesBody: 'Un lot restreint, une qualification expirée, un marché secondaire en pause et un solde faible.',
    presetActive: 'Point de départ actuel',
    presetSwitch: 'Charger ce point de départ',
    presetSwitchWarning: 'Charger un autre point de départ remplace la progression actuelle.',
    advance: 'Avancer la date simulée',
    advanceBody: 'L’horloge simulée passe du {from} au {to}. Cette étape ne modifie aucun enregistrement commercial.',
    stage: { balanceDue: '15 février 2027 — solde à régler', ready: '15 juin 2027 — lot prêt à livrer' },
    tourStep: 'Étape {index} sur {total}',
    tourNext: 'Suivant',
    tourPrevious: 'Précédent',
    tourPause: 'Suspendre la visite',
    tourResume: 'Reprendre la visite',
    tourClose: 'Fermer la visite',
    tourGo: 'Ouvrir cet écran',
    tourFinished: 'Visite guidée terminée',
    tourFinishedBody:
      'Toutes les étapes de ce scénario ont utilisé le même registre fictif. La réinitialisation le ramène à son point de départ.',
    simulate: 'Simuler : {action}',
    simulationComplete: 'Simulation terminée',
    localReference: 'Référence locale de démonstration',
    syntheticNotice:
      'Organisations, vins et prix fictifs. Rien ici ne passe commande ni ne transfère de fonds réels.',
    storedLocally: '{count} actions fictives enregistrées dans ce navigateur',
  },
  testnet: {
    title: 'Accès testnet',
    lead: 'Il s’agit d’un environnement technique distinct. Il utilise des actifs de test sur un réseau configuré et ne touche jamais à des fonds réels.',
    checks: 'Vérifications de l’environnement',
    checkChain: 'Identifiant du réseau',
    checkRpc: 'Point d’accès réseau',
    checkAddresses: 'Adresses des contrats',
    checkBytecode: 'Bytecode déployé',
    checkToken: 'Jeton de paiement et décimales',
    checkAccount: 'Compte connecté',
    checkQualification: 'Qualification du participant',
    observed: 'Observé',
    missing: 'Absent',
    failed: 'Échec',
    unavailable: 'Indisponible',
    connect: 'Connecter un portefeuille',
    enter: 'Entrer dans l’espace',
    blocked: 'La configuration testnet est incomplète.',
    blockedBody:
      'Le manifeste de déploiement de cette version ne contient pas de configuration testnet validée : aucune action d’écriture n’est proposée ici.',
    mainnet: 'Le réseau principal n’est pas activé pour ce prototype',
    noKeys: 'Ne saisissez jamais de phrase de récupération ni de clé privée. Palissage ne les demande pas.',
    demoLink: 'Ouvrir la démo interactive',
    supported: 'Actions prises en charge',
    readOnly: 'Lecture seule dans cette version',
  },
  pilot: {
    title: 'Construire une nouvelle voie pour le commerce du vin.',
    sections: {
      who: 'À qui s’adresse le pilote',
      whoBody:
        'Des domaines indépendants qui ont du vin à placer et des acheteurs professionnels qui achètent régulièrement : cavistes, restaurants et importateurs. Ce n’est pas un produit d’investissement grand public.',
      what: 'Ce que montre le prototype',
      whatBody:
        'Création du lot, examen, réservation, paiement du solde, revente éligible et demande de livraison. Parcours simulés et enregistrements testnet identifiés séparément.',
      stage: 'État actuel',
      stageBody: 'Développement du prototype et du testnet. Les échanges sur le réseau principal ne sont pas activés.',
      technology: 'Technologie',
      technologyBody:
        'Soldes de bouteilles, vérification des participants, transferts contrôlés et historique des paiements. Le dépôt actuel vise un environnement de test EVM ; les preuves de déploiement sont présentées séparément.',
      milestones: 'Prochains jalons',
      support: 'Ce que permet le soutien',
      supportBody:
        'Ingénierie, validation UX, préparation juridique et opérationnelle, audit de sécurité indépendant et intégration des participants au pilote.',
      enquiry: 'Préparer une demande pour le pilote',
    },
    milestones: [
      'Finaliser le parcours de test',
      'Valider avec les participants du pilote',
      'Finaliser les modalités opérationnelles et juridiques',
      'Audit de sécurité indépendant',
      'Pilote encadré en conditions réelles',
    ],
    planned: 'Prévu',
    form: {
      organisation: 'Organisation',
      contact: 'Nom du contact',
      email: 'Adresse e-mail professionnelle',
      role: 'Rôle',
      roleOptions: {
        winery: 'Domaine',
        importer: 'Importateur',
        shop: 'Caviste',
        restaurant: 'Restaurant',
        other: 'Autre professionnel',
      },
      country: 'Pays',
      website: 'Site web',
      message: 'Message',
      hint: 'N’indiquez ni coordonnées bancaires, ni pièce d’identité, ni information commercialement sensible.',
      submit: 'Télécharger le brouillon',
      success: 'Brouillon téléchargé. Aucun message n’a été envoyé.',
      privacy: 'Confidentialité',
    },
  },
  legal: {
    privacy: 'Confidentialité',
    prototype: 'Notice du prototype',
    credits: 'Crédits photos',
    documentStatus: 'Brouillon · environnement de test',
    contents: 'Sur cette page',
    prototypeBody:
      'Palissage est un prototype pour le commerce professionnel du vin. Les actions de démonstration sont simulées et ne passent aucune commande, ne transfèrent aucun fonds réel et n’organisent aucune livraison. Les actions testnet utilisent des actifs de test. Les conditions commerciales réelles seront établies avant le lancement des échanges.',
    privacyBody:
      'La démo conserve votre progression fictive et votre langue dans ce navigateur. La réinitialisation efface cette progression. Ne saisissez aucun document d’identité ni donnée personnelle sensible. L’expérience testnet peut transmettre votre adresse publique et vos requêtes aux fournisseurs réseau configurés.',
    creditsBody:
      'Les illustrations de ce prototype sont générées pour la démonstration et ne relèvent d’aucune licence tierce. Toute photographie est ajoutée via le manifeste des médias, avec sa source et sa licence.',
    publisherPending:
      'L’éditeur, l’entité juridique et l’hébergeur seront renseignés avant toute publication externe. Ils ne sont pas inventés ici.',
  },
  footer: {
    purpose: 'Un prototype pour le commerce direct entre domaines indépendants et acheteurs professionnels.',
    pilot: 'Projet pilote',
    testnet: 'Testnet',
    prototype: 'Notice du prototype',
    privacy: 'Confidentialité',
    credits: 'Crédits photos',
    notice: 'Prototype de commerce professionnel · Aucune commande réelle de vin · 18+',
    health: 'L’abus d’alcool est dangereux pour la santé. À consommer avec modération.',
  },
  passport: {
    title: 'L’histoire de ce lot',
    sourceNote:
      'Passeport de lot de démonstration. Scanner ce code ne vérifie pas une bouteille unique et ne confère aucun droit de propriété.',
    demoLabel: 'Passeport de démonstration',
    wine: 'Vin',
    producer: 'Producteur',
    timeline: 'Étapes de production',
    records: 'Justificatifs publics',
    copyLink: 'Copier le lien',
    explore: 'Découvrir Palissage',
    viewLot: 'Voir le lot public',
    notRecorded: 'Non enregistré',
  },
  buyer: {
    overview: 'Vue d’ensemble',
    actionRequired: 'Action requise',
    nothingDue: 'Rien ne requiert votre attention pour le moment.',
    remainderDue: 'Solde à régler',
    bottlesHeld: 'Bouteilles détenues',
    bottlesInEscrow: 'Bouteilles bloquées pour livraison',
    spendable: 'Solde fictif',
    recentActivity: 'Activité récente',
    allocations: 'Réservations et bouteilles',
    tabs: { reservations: 'Réservations', balances: 'Soldes de bouteilles', history: 'Historique' },
    filters: { all: 'Toutes', due: 'Solde à régler', paid: 'Intégralement payé', closed: 'Clôturées' },
    columns: {
      lot: 'Lot',
      producer: 'Producteur',
      quantity: 'Quantité initiale',
      paid: 'Payé / total',
      due: 'Solde à régler',
      deadline: 'Échéance',
      state: 'État',
      action: 'Action suivante',
      walletQuantity: 'En portefeuille',
      frozen: 'Restreint',
      escrow: 'Séquestre livraison',
      transferable: 'Disponible',
      reference: 'Référence',
      bottles: 'Bouteilles',
      winery: 'Domaine',
      requested: 'Demandé le',
      price: 'Prix / bouteille',
      seller: 'Vendeur',
      available: 'Disponible',
      royalty: 'Redevance du domaine',
      remaining: 'Restant',
      initial: 'Initial',
      date: 'Date',
      event: 'Événement',
      source: 'Source',
    },
    payRemainder: 'Régler le solde',
    payRemainderDemo: 'Simuler le paiement du solde',
    viewAllocation: 'Voir la réservation',
    viewPosition: 'Voir la position',
    allocationDetail: 'Détail de la réservation',
    paymentSchedule: 'Échéancier',
    bottleAccounting: 'Comptabilité des bouteilles',
    ownershipNote: 'Les jetons sont créés après paiement intégral.',
    position: 'Position en bouteilles',
    acquisitions: 'Acquisitions et transferts',
    listForResale: 'Créer une offre de revente',
    requestDelivery: 'Demander la livraison',
    secondary: 'Marché secondaire',
    secondaryTabs: { browse: 'Parcourir les annonces', mine: 'Mes annonces' },
    secondaryContext:
      'La revente transfère des droits sur des bouteilles existantes entre acheteurs éligibles. Chaque vente verse une redevance au producteur.',
    createListing: 'Créer une offre de revente',
    cancelListing: 'Annuler l’annonce',
    viewListing: 'Voir l’annonce',
    buyListing: 'Examiner l’achat',
    deliveries: 'Livraisons',
    deliveryDetail: 'Détail de la livraison',
    confirmReceipt: 'Confirmer la réception',
    reportProblem: 'Signaler un problème de livraison',
    cancelRequest: 'Annuler la demande',
    destination: 'Adresse de livraison',
    shipmentDocuments: 'Documents d’expédition',
    supportCases: 'Dossiers d’assistance',
    reserveTitle: 'Réserver une quantité',
    steps: { terms: 'Conditions', review: 'Récapitulatif', result: 'Résultat' },
    paymentChoice: 'Paiement',
    payFull: 'Régler la totalité',
    payDeposit: 'Régler l’acompte minimum',
    acknowledge: 'Je comprends qu’il s’agit d’un environnement de test et qu’aucun vin n’est commandé.',
    account: 'Compte et éligibilité',
  },
  winery: {
    overview: 'Vue d’ensemble',
    lots: 'Lots de vin',
    createLot: 'Créer le brouillon du lot',
    lotDetail: 'Gérer le lot',
    finance: 'Paiements et versements',
    deliveries: 'Livraisons',
    fundsReceived: 'Montant brut reçu',
    feesDeducted: 'Frais de protocole déduits',
    netCredited: 'Net crédité',
    lockedEscrow: 'Bloqué selon les règles de versement',
    withdrawable: 'Disponible au retrait',
    withdrawn: 'Déjà retiré',
    royaltiesEarned: 'Redevances producteur',
    tabs: {
      overview: 'Vue d’ensemble',
      documents: 'Documents',
      offers: 'Offres',
      production: 'Production',
      history: 'Historique',
      escrow: 'Séquestre primaire',
      royalties: 'Redevances',
      withdrawals: 'Retraits',
    },
    wizard: {
      identity: 'Identité du vin',
      quantity: 'Quantité et production',
      evidence: 'Justificatifs',
      review: 'Récapitulatif',
      next: 'Continuer',
      back: 'Retour',
      createDraft: 'Créer le brouillon du lot',
      submit: 'Soumettre à l’examen',
      draftNote: 'Un brouillon enregistré reste dans ce navigateur jusqu’à la création du lot.',
    },
    createOffer: 'Créer une offre',
    publishOffer: 'Publier l’offre',
    cancelOffer: 'Retirer l’offre',
    advanceProduction: 'Mettre à jour la production',
    submitEvidence: 'Soumettre les justificatifs du jalon',
    withdraw: 'Retirer les fonds disponibles',
    recordShipment: 'Enregistrer l’expédition',
    exportCsv: 'Télécharger les lignes affichées (CSV)',
    milestones: 'Jalons de versement',
    milestoneReleased: 'Débloqué',
    milestonePending: 'En attente de confirmation',
    remaining: 'Encore proposable',
    noOffers: 'Aucune offre publiée pour ce lot.',
    offerable: '{count} bouteilles peuvent encore être proposées',
    account: 'Compte et éligibilité',
  },
  operations: {
    overview: 'Files d’attente opérationnelles',
    banner: 'Espace opérations de démonstration',
    participants: 'Participants',
    participantDetail: 'Examen du participant',
    verification: 'Examen des lots',
    verificationDetail: 'Justificatifs et décisions',
    redemptions: 'Livraisons à examiner',
    redemptionDetail: 'Dossier de livraison',
    queues: {
      participants: 'Participants en attente d’examen',
      lots: 'Lots en attente d’examen',
      milestones: 'Jalons en attente de confirmation',
      cases: 'Dossiers de livraison ouverts',
    },
    tabs: { lots: 'Lots', milestones: 'Jalons' },
    decision: 'Décision',
    approve: 'Approuver',
    requestChanges: 'Demander des modifications',
    reject: 'Refuser la demande',
    recordReview: 'Enregistrer l’examen du lot',
    confirmMilestone: 'Confirmer le jalon',
    checklist: 'Points à vérifier',
    checklistItems: [
      'Les justificatifs de l’organisation ont été consultés',
      'Le rôle du participant correspond à l’activité déclarée',
      'Les attestations requises sont présentes',
      'Le périmètre et le pays déclarés ont été examinés',
    ],
    lotChecklist: [
      'Le producteur déclaré correspond au propriétaire du lot',
      'La quantité et la contenance sont cohérentes avec l’enregistrement',
      'Les justificatifs de provenance ont été consultés',
      'L’étape de production correspond aux documents soumis',
    ],
    grants: 'Autorisations contractuelles',
    grantsNote:
      'Chaque autorisation est lue depuis le contrat qui la détient. Un rôle métier ne l’élargit jamais.',
    refreshGrants: 'Actualiser les autorisations',
    resolveCase: 'Clore le dossier',
    outcomeDelivery: 'Confirmer la livraison',
    outcomeReturn: 'Restituer les bouteilles tokenisées',
    outcomeReturnNote:
      'Restituer les jetons de bouteilles séquestrés. Cette action n’effectue aucun remboursement monétaire.',
    enforcement: 'Mesures d’exécution et récupération',
    enforcementBody:
      'Le gel, le transfert forcé et la récupération d’un séquestre nécessitent un parcours spécialisé avec sa propre autorisation. Ils sont présentés ici en lecture seule et ne font pas partie de l’examen courant.',
    account: 'Compte et autorisations',
  },
  price: {
    unit: 'Par bouteille · 750 ml',
    exclusions:
      'Prix de la quantité de vin. Transport, taxes, droits et frais réseau non inclus dans cet exemple.',
    settlementNote: 'Le transport et les taxes applicables font l’objet d’un devis distinct.',
    precision: 'Précision de règlement du jeton',
    exactAmount: 'Montant exact',
  },
  order: {
    total: 'Montant total',
    deposit: 'Acompte à régler',
    balance: 'Solde restant',
    payNow: 'À régler maintenant',
    deadline: 'Solde à régler avant le {date}',
    reserveDemo: 'Simuler la réservation',
    reserveTest: 'Réserver {quantity} bouteilles',
    payDemo: 'Simuler le paiement du solde',
    payTest: 'Régler le solde',
    feeIncluded:
      'Les frais de plateforme de {rate} sont inclus dans le montant brut et déduits du versement au domaine.',
    quantityUnit: 'bouteilles',
  },
  approval: {
    title: 'Autoriser le paiement',
    body: 'Cette autorisation permet au contrat de marché de dépenser le montant affiché. Elle ne réserve aucune bouteille.',
    done: 'Autorisation confirmée. Poursuivez la réservation.',
  },
  tx: {
    wallet: 'Confirmer dans votre portefeuille',
    pending: 'Transaction envoyée. En attente de confirmation.',
    checking: 'Vérification de l’enregistrement mis à jour…',
    rejected: 'Demande refusée. Aucune nouvelle transaction n’a été envoyée.',
    unknown: 'La confirmation prend plus de temps. Vérifiez la transaction avant de réessayer.',
    reverted:
      'La transaction a échoué. Votre réservation n’a pas changé. Des frais réseau peuvent toutefois s’appliquer.',
    confirm: 'Confirmer',
    review: 'Récapitulatif',
    consequences: 'Ce qui se passe ensuite',
    working: 'En cours…',
  },
  reserve: {
    done: '{quantity} bouteilles réservées. Acompte enregistré.',
    depositNote: 'Les jetons sont créés après paiement intégral.',
  },
  paid: { done: 'Paiement intégral · {quantity} bouteilles' },
  secondary: {
    list: 'Créer une offre de revente',
    royalty: 'Redevance du domaine',
    proceeds: 'Montant reçu par le vendeur',
    fee: 'Frais de plateforme',
    gross: 'Montant payé par l’acheteur',
    unitPrice: 'Prix par bouteille',
    listingRemaining: '{remaining} bouteilles restantes sur {initial}',
    noExpiry:
      'Une annonce n’a pas d’échéance propre. Le devis confirmé au moment de l’achat comporte un court délai.',
    unavailable: 'Indisponible',
    unavailableBody:
      'Le solde du vendeur a évolué depuis la création de cette annonce : elle ne peut pas être honorée actuellement.',
  },
  delivery: {
    request: 'Demander la livraison',
    escrow: 'Les bouteilles demandées sont bloquées pendant la livraison.',
    confirm: 'Confirmer la réception',
    confirmBody:
      'Confirmez uniquement après réception du vin. Cette étape clôture la demande et retire le solde de bouteilles tokenisées correspondant.',
    confirmCheckbox: 'Je confirme la réception du vin décrit ci-dessus',
    problem: 'Signaler un problème de livraison',
    tokenReturn: 'Solde de bouteilles tokenisées rétabli',
    logisticsNote:
      'La logistique, le transport, les taxes et les droits sont convenus séparément. Cette demande ne réserve aucun transporteur.',
    recorded: 'Expédition enregistrée',
    noTracking: 'Aucun suivi transporteur n’est connecté dans cette version.',
    useFictional: 'Utiliser des coordonnées fictives',
    categories: {
      missing: 'Expédition manquante',
      damaged: 'Endommagé ou incomplet',
      documentation: 'Documentation',
      other: 'Autre',
    },
    description: 'Description',
    prepareRequest: 'Préparer une demande d’assistance',
  },
  common: {
    evidence: 'Voir les justificatifs',
    technical: 'Enregistrement technique',
    retry: 'Réessayer',
    back: 'Retour',
    cancel: 'Annuler',
    close: 'Fermer',
    saveDraft: 'Enregistrer le brouillon',
    saved: 'Brouillon enregistré dans ce navigateur',
    notProvided: 'Non renseigné',
    notProvidedSample: 'Non renseigné dans cet exemple',
    copy: 'Copier',
    copyDone: 'Copié',
    download: 'Télécharger le récapitulatif',
    loading: 'Chargement',
    updating: 'Actualisation',
    lastUpdated: 'Dernière mise à jour {time}',
    source: 'Source',
    showMore: 'Afficher plus',
    showLess: 'Afficher moins',
    required: 'Obligatoire',
    optional: 'Facultatif',
    continue: 'Continuer',
    confirm: 'Confirmer',
    yes: 'Oui',
    no: 'Non',
    all: 'Tous',
    none: 'Aucun',
    search: 'Rechercher',
    of: 'sur',
    unknown: 'Inconnu',
    viewAll: 'Tout afficher',
    openDocument: 'Ouvrir le document',
    documentMeta: '{type} · {size}',
    sampleDocument: 'Document de démonstration',
    demoVerification: 'Vérification de démonstration',
    illustrative: 'Photographie d’illustration',
    illustrativeImage: 'Illustration générée pour cette démonstration',
    errorSummary: 'Vérifiez les points suivants',
    unsavedChanges: 'Modifications non enregistrées',
    keepEditing: 'Continuer la saisie',
    discard: 'Abandonner les modifications',
    remove: 'Retirer',
    add: 'Ajouter',
    step: 'Étape',
    quantityAvailable: '{count} disponibles',
  },
  status: {
    lot: {
      Draft: 'Brouillon',
      Verified: 'Examen du lot enregistré',
      Suspended: 'Lot restreint',
      Closed: 'Lot clôturé',
    },
    production: {
      Announced: 'Annoncé',
      Growing: 'En culture',
      Harvested: 'Vendangé',
      Vinification: 'Vinification',
      Aging: 'Élevage',
      Bottled: 'Mis en bouteille',
      ReadyForDelivery: 'Prêt à livrer',
    },
    allocation: {
      Reserved: 'Réservé · Solde à régler',
      Paid: 'Intégralement payé',
      Cancelled: 'Réservation annulée',
      Defaulted: 'Défaut de paiement enregistré',
    },
    redemption: {
      Requested: 'Livraison demandée',
      Shipped: 'Expédition enregistrée',
      Completed: 'Réception confirmée',
      Cancelled: 'Demande de livraison annulée',
    },
    review: {
      draft: 'Brouillon',
      submitted: 'En attente d’examen',
      needs_changes: 'Modifications demandées',
      accepted: 'Examen accepté',
      rejected: 'Examen refusé',
    },
    case: {
      open: 'Problème de livraison signalé',
      under_review: 'Dossier en cours d’examen',
      resolved_delivery: 'Dossier clos · livraison confirmée',
      resolved_return: 'Dossier clos · bouteilles restituées',
    },
    offer: {
      open: 'Ouvert aux réservations',
      scheduled: 'Ouvre le {date}',
      ended: 'Réservations closes',
      sold_out: 'Entièrement attribué',
      cancelled: 'Offre retirée',
    },
    listing: { active: 'Active', sold: 'Vendue', cancelled: 'Annulée', unavailable: 'Indisponible' },
    overdue: 'Paiement en retard',
  },
  field: {
    wineName: 'Nom du vin',
    vintage: 'Millésime',
    region: 'Région',
    country: 'Pays',
    grapes: 'Cépages',
    bottleSize: 'Contenance',
    alcohol: 'Titre alcoométrique',
    quantity: 'Nombre de bouteilles',
    price: 'Prix par bouteille',
    deposit: 'Pourcentage d’acompte',
    saleStart: 'Ouverture des réservations',
    saleEnd: 'Clôture des réservations',
    paymentDeadline: 'Échéance du solde',
    expectedReady: 'Date de disponibilité prévue',
    documents: 'Justificatifs',
    organisation: 'Organisation',
    contact: 'Nom du contact',
    email: 'Adresse e-mail professionnelle',
    phone: 'Téléphone',
    address: 'Adresse de livraison',
    addressLine2: 'Complément d’adresse',
    city: 'Ville',
    postcode: 'Code postal',
    notes: 'Remarques',
    reason: 'Motif de la décision',
    royalty: 'Redevance du domaine',
    offerType: 'Type d’offre',
    carrier: 'Transporteur',
    trackingReference: 'Référence d’expédition',
    shippedDate: 'Date d’expédition',
    trackingUrl: 'Lien de suivi',
    percentage: 'Pourcentage',
    grapeName: 'Cépage',
  },
  action: {
    createLot: 'Créer le brouillon du lot',
    submitReview: 'Soumettre à l’examen',
    requestChanges: 'Demander des modifications',
    recordReview: 'Enregistrer l’examen du lot',
    publishOffer: 'Publier l’offre',
    updateProduction: 'Mettre à jour la production',
    confirmMilestone: 'Confirmer le jalon',
    withdraw: 'Retirer les fonds disponibles',
    markShipped: 'Enregistrer l’expédition',
    returnTokens: 'Restituer les bouteilles tokenisées',
  },
  activity: {
    'allocation.reserved': '{actor} a réservé {quantity} bouteilles',
    'allocation.paid': '{actor} a réglé le solde',
    'listing.created': '{actor} a proposé {quantity} bouteilles à la revente',
    'listing.cancelled': '{actor} a annulé une annonce',
    'listing.filled': '{actor} a acheté {quantity} bouteilles sur le marché secondaire',
    'redemption.requested': '{actor} a demandé la livraison',
    'redemption.shipped': '{actor} a enregistré l’expédition',
    'redemption.completed': '{actor} a confirmé la réception',
    'redemption.cancelled': '{actor} a annulé la demande de livraison',
    'redemption.refunded': '{actor} a restitué les bouteilles séquestrées',
    'lot.created': '{actor} a créé un brouillon de lot',
    'lot.submitted': '{actor} a soumis le lot à l’examen',
    'lot.changes_requested': '{actor} a demandé des modifications du lot',
    'lot.verified': '{actor} a enregistré l’examen du lot',
    'lot.production': '{actor} a mis à jour l’étape de production',
    'offer.published': '{actor} a publié une offre',
    'offer.cancelled': '{actor} a retiré une offre',
    'milestone.evidence': '{actor} a soumis les justificatifs d’un jalon',
    'milestone.confirmed': '{actor} a confirmé un jalon de versement',
    'funds.withdrawn': '{actor} a retiré les fonds disponibles',
    'case.opened': '{actor} a signalé un problème de livraison',
    'case.resolved': '{actor} a clos le dossier de livraison',
    'participant.reviewed': '{actor} a enregistré l’examen d’un participant',
    'clock.advanced': 'Date simulée avancée',
  },
  empty: {
    noResults: {
      title: 'Aucun lot correspondant',
      body: 'Essayez un autre producteur, millésime ou prix.',
      action: 'Effacer les filtres',
    },
    noAllocations: {
      title: 'Votre prochaine réservation commence ici',
      body: 'Explorez les offres et leurs conditions.',
      action: 'Voir les lots',
    },
    noDeliveries: {
      title: 'Aucune demande de livraison',
      body: 'Demandez la livraison de vos bouteilles prêtes et intégralement payées.',
      action: 'Voir mes réservations',
    },
    noListings: {
      title: 'Aucune annonce',
      body: 'Les bouteilles éligibles peuvent être proposées à la revente depuis une position.',
      action: 'Voir les soldes de bouteilles',
    },
    noQueue: {
      title: 'Aucun élément en attente d’examen',
      body: 'Les nouvelles demandes apparaissent ici dès leur envoi.',
      action: '',
    },
    noLots: {
      title: 'Aucun lot',
      body: 'Créez un brouillon de lot avec sa quantité, son étape de production et ses justificatifs.',
      action: 'Créer le brouillon du lot',
    },
    noActivity: { title: 'Aucune activité', body: 'Les actions de ce scénario apparaissent ici.', action: '' },
  },
  errors: {
    wrongNetwork: {
      title: 'Passer sur {network}',
      body: 'Cette action testnet est indisponible sur le réseau actuel.',
      action: 'Changer de réseau',
    },
    unverifiedBuyer: {
      title: 'Vérification requise',
      body: 'Votre compte doit disposer des vérifications acheteur nécessaires.',
      action: 'Voir le compte',
    },
    rpcUnavailable: {
      title: 'Enregistrements réseau indisponibles',
      body: 'Les données existantes n’ont pas été remplacées. Reconnectez-vous pour les actualiser.',
      action: 'Réessayer',
    },
    lotUnavailable: {
      title: 'Ce lot est indisponible',
      body: 'Ce lot est introuvable dans l’environnement choisi.',
      action: 'Retour au catalogue',
    },
    readOnly: {
      title: 'Action indisponible dans cet environnement',
      body: 'L’intégration ou l’autorisation nécessaire est indisponible.',
      action: 'Voir les détails',
    },
    frozen: {
      title: 'Ce solde est temporairement indisponible',
      body: 'Consultez la restriction et les possibilités d’assistance.',
      action: 'Voir la restriction',
    },
    soldOut: {
      title: 'Entièrement attribué',
      body: 'Cette offre primaire n’a plus de quantité disponible.',
      action: 'Voir les offres secondaires',
    },
    notFound: { title: 'Introuvable', body: 'Ce {entity} n’existe pas dans l’environnement choisi.', action: 'Retour' },
    generic: 'Cette action n’a pas pu aboutir. Le dernier enregistrement confirmé est affiché.',
    persistedVersion: {
      title: 'La progression fictive n’a pas pu être restaurée',
      body: 'La session enregistrée ne correspond pas à cette version. La réinitialiser démarre un scénario propre.',
      action: 'Réinitialiser les données fictives',
    },
  },
  reason: {
    UNKNOWN: 'Cette vérification n’a pas pu aboutir : l’action reste indisponible.',
    NOT_CONNECTED: 'Choisissez un rôle dans la démo, ou connectez un compte en testnet.',
    WRONG_ROLE: 'Ce compte occupe un autre rôle dans le parcours.',
    NOT_OWNER: 'Cet enregistrement appartient à une autre organisation.',
    NOT_ELIGIBLE: 'Votre compte doit disposer des vérifications acheteur nécessaires.',
    ELIGIBILITY_EXPIRED: 'Une qualification requise a expiré et doit être réexaminée.',
    LOT_NOT_VERIFIED: 'L’examen de ce lot n’est pas terminé.',
    LOT_SUSPENDED: 'Ce lot est temporairement restreint.',
    LOT_CLOSED: 'Ce lot est clôturé.',
    MARKET_PAUSED: 'Ce marché est en pause : l’action est temporairement restreinte.',
    OFFER_NOT_OPEN: 'Cette offre n’est pas ouverte aux réservations.',
    OFFER_SOLD_OUT: 'Cette offre primaire n’a plus de quantité disponible.',
    DEADLINE_PASSED: 'L’échéance de paiement est dépassée.',
    NOT_READY_FOR_DELIVERY: 'La livraison s’ouvre lorsque le lot est indiqué comme prêt.',
    NO_TRANSFERABLE_BALANCE: 'Aucune bouteille disponible dans cette position.',
    BALANCE_FROZEN: 'Ce solde est restreint et ne peut pas être utilisé actuellement.',
    NOTHING_WITHDRAWABLE: 'Aucun versement confirmé n’est disponible au retrait.',
    ALREADY_SETTLED: 'Cette étape est déjà terminée.',
    WRONG_STATE: 'L’état de cet enregistrement ne permet pas cette action.',
    MISSING_EVIDENCE: 'Les justificatifs requis n’ont pas été fournis.',
    MISSING_CONTRACT_ROLE: 'Votre compte ne détient pas l’autorisation exigée par ce contrat.',
    INTEGRATION_UNAVAILABLE: 'L’intégration nécessaire est indisponible dans cette version.',
    SELF_TRADE: 'Un vendeur ne peut pas acheter sa propre annonce.',
    INSUFFICIENT_FUNDS: 'Solde de jetons de test insuffisant.',
    QUOTE_CHANGED: 'Le devis a changé ou a expiré.',
    STALE_SNAPSHOT: 'Les enregistrements ont changé pendant l’examen. Vérifiez les montants actualisés.',
    DUPLICATE_REQUEST: 'Cette action a déjà été envoyée.',
  },
  validation: {
    required: 'Ce champ est obligatoire.',
    tooShort: 'Utilisez au moins {min} caractères.',
    tooLong: 'Utilisez au plus {max} caractères.',
    email: 'Saisissez une adresse e-mail valide.',
    url: 'Saisissez une adresse valide.',
    https: 'Utilisez une adresse https://.',
    wholeNumber: 'Saisissez un nombre entier.',
    quantityRange: 'Saisissez un nombre entier de bouteilles, de {min} à {max}.',
    quantityStep: 'Utilisez un multiple de {step} bouteilles.',
    noneAvailable: 'Aucune bouteille disponible pour cette action.',
    priceFormat: 'Saisissez un montant tel que {example}.',
    pricePrecision: 'Utilisez au plus {decimals} décimales.',
    pricePositive: 'Saisissez un montant supérieur à zéro.',
    vintageRange: 'Saisissez une année entre {min} et {max}.',
    abvFormat: 'Saisissez une valeur telle que {example}.',
    abvRange: 'Saisissez une valeur entre {min} et {max}.',
    percentageRange: 'Saisissez un pourcentage entre 0 et 100.',
    percentageSum: 'Le total des pourcentages est {sum}. Il doit atteindre 100 lorsque chaque cépage en comporte un.',
    tooManyRows: 'Ajoutez au plus {max} cépages.',
    endAfterStart: 'La date de clôture doit suivre la date d’ouverture.',
    deadlineAfterEnd: 'L’échéance du solde ne peut pas précéder la clôture des réservations.',
    depositRange: 'Saisissez un acompte entre 1 % et 99 %.',
    depositBelowPrecision: 'Le montant de l’acompte est inférieur à la précision prise en charge.',
    enPrimeurProduction: 'La vente en primeur s’applique avant la mise en bouteille.',
    postalCodeFr: 'Un code postal français comporte cinq chiffres.',
    summary: 'Vérifiez {count} champs avant de continuer.',
  },
  a11y: {
    mainNavigation: 'Navigation principale',
    workspaceNavigation: 'Navigation de l’espace de travail',
    breadcrumb: 'Fil d’Ariane',
    sortBy: 'Trier les résultats par',
    increase: 'Augmenter la quantité',
    decrease: 'Diminuer la quantité',
    openMenu: 'Ouvrir le menu',
    resultsUpdated: '{count} lots trouvés',
    dialog: 'Fenêtre de récapitulatif',
    progress: 'Progression',
    lotImage: 'Illustration de la bouteille fictive {name}',
    heroImage: 'Illustration de rangs de vigne générée pour cette démonstration',
    estateImage: 'Illustration de chai générée pour cette démonstration',
  },
};
